import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from './Header';
import React, { Suspense } from 'react';
import QueryProvider from '@/app/lib/queryProvider';
import dynamic from 'next/dynamic';

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
});

export const metadata: Metadata = {
  title: 'Tiing',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

const HeaderClient = dynamic(() => import('./Header'), { ssr: false });

export default function RootLayout({
  auth,
  children,
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <QueryProvider>
          <Suspense fallback={<div>Loading...</div>}>
            <HeaderClient />
            <div>{auth}</div>
            <div id="children-container">{children}</div>
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
